app/config/AppConfig.scala, app/connectors/GetPensionReliefsConnector.scala, app/connectors/httpParsers/GetPensionReliefsHttpParser.scala, app/controllers/GetPensionReliefsController.scala, app/models/DesErrorBody.scala, app/models/GetPensionReliefsModel.scala, app/services/GetPensionReliefsService.scala, conf/app.routes, it/api/GetPensionReliefsITest.scala, it/connectors/GetPensionReliefsConnectorISpec.scala, project/AppDependencies.scala, test/models/GetPensionReliefsModelSpec.scala
Connecting income-tax-pensions backend microservice through to the DES API #1656 (The GET pension reliefs API).
Subtask SASS-1873 for [SASS-1714](https://jira.tools.tax.service.gov.uk/browse/SASS-1714)
=> SASS-1873 add GET pension reliefs API 1656

app/common/EnrolmentCommon.scala, app/config/AppConfig.scala, app/config/Modules.scala, app/connectors/DesConnector.scala, app/connectors/GetPensionChargesConnector.scala, app/connectors/httpParsers/DESParser.scala, app/connectors/httpParsers/GetPensionChargesHttpParser.scala, app/controllers/GetPensionChargesController.scala, app/controllers/predicates/AuthorisedAction.scala, app/models/DesErrorBody.scala, app/models/GetPensionChargesRequestModel.scala, app/models/GetPensionReliefsModel.scala, app/models/User.scala, app/services/AuthService.scala, app/services/GetPensionChargesService.scala, app/services/GetPensionReliefsService.scala, app/utils/HeaderCarrierSyntax.scala, app/utils/PagerDutyHelper.scala, conf/app.routes, conf/application.conf, it/api/GetPensionChargesITest.scala, it/connectors/GetPensionChargesConnectorSpec.scala, it/connectors/GetPensionReliefsConnectorISpec.scala, it/helpers/AuthStub.scala, it/helpers/WireMockHelper.scala, it/helpers/WiremockSpec.scala, it/helpers/WiremockStubHelpers.scala, test/models/GetPensionChargesRequestModelSpec.scala
Implement GET pension charges API 1674
[SASS-1715](https://jira.tools.tax.service.gov.uk/browse/SASS-1715)
=> SASS-1715 implement GET pension charges API 1674

app/connectors/PensionChargesConnector.scala, app/connectors/PensionReliefsConnector.scala, app/connectors/httpParsers/DeletePensionChargesHttpParser.scala, app/controllers/PensionChargesController.scala, app/controllers/PensionReliefsController.scala, app/services/PensionChargesService.scala, app/services/PensionReliefsService.scala, conf/app.routes, it/api/DeletePensionChargesITest.scala, it/connectors/PensionChargesConnectorSpec.scala, it/connectors/PensionReliefsConnectorISpec.scala, scalastyle-config.xml, test/connectors/DesConnectorSpec.scala, test/connectors/httpParsers/DESParserSpec.scala, test/controllers/predicates/AuthorisedActionSpec.scala, test/models/DesErrorBodyModelSpec.scala, test/models/GetPensionChargesRequestModelSpec.scala, test/models/GetPensionReliefsModelSpec.scala, test/models/UserSpec.scala, test/utils/DESTaxYearHelperSpec.scala, test/utils/PagerDutyHelperTest.scala, test/utils/TestUtils.scala
Add delete pension charges API
[1785](https://jira.tools.tax.service.gov.uk/browse/SASS-1785)
=> SASS-1785 add delete pension charges API

app/connectors/PensionReliefsConnector.scala, app/connectors/httpParsers/DeletePensionReliefsHttpParser.scala, app/controllers/PensionReliefsController.scala, app/services/PensionReliefsService.scala, conf/app.routes, it/api/DeletePensionReliefsITest.scala, it/connectors/PensionReliefsConnectorISpec.scala
Pensions - DELETE pension reliefs API (1657).
[SASS-1787](https://jira.tools.tax.service.gov.uk/browse/SASS-1787)
=> SASS-1787 Delete Pension Reliefs

app/connectors/PensionReliefsConnector.scala, app/connectors/httpParsers/CreateOrAmendPensionReliefsHttpParser.scala, app/controllers/PensionReliefsController.scala, app/models/CreateOrUpdatePensionReliefsModel.scala, app/services/PensionReliefsService.scala, conf/app.routes, it/api/CreateOrAmendPensionReliefsITest.scala, it/connectors/PensionReliefsConnectorISpec.scala
Add create or update pension reliefs endpoint
[SASS-1789](https://jira.tools.tax.service.gov.uk/browse/SASS-1789)
=> SASS-1789 Add create or amend pension charges

app/connectors/PensionChargesConnector.scala, app/connectors/httpParsers/CreateUpdatePensionChargesHttpParser.scala, app/controllers/PensionChargesController.scala, app/models/CreateUpdatePensionChargesRequestModel.scala, app/models/DesErrorBody.scala, app/services/PensionChargesService.scala, conf/app.routes, it/api/CreateUpdatePensionChargesITest.scala, it/connectors/PensionChargesConnectorISpec.scala
Added CREATE/UPDATE pension charges API (1673)
[SASS-1786](https://jira.tools.tax.service.gov.uk/browse/SASS-1786)
=> SASS-1786 create/update pension charges API

app/connectors/StateBenefitsConnector.scala, app/connectors/httpParsers/DeleteOverrideStateBenefitHttpParser.scala, app/controllers/PensionChargesController.scala, app/controllers/StateBenefitsController.scala, app/models/DesErrorBody.scala, app/services/StateBenefitsService.scala, conf/app.routes, it/api/DeleteOverrideStateBenefitsITest.scala, it/connectors/StateBenefitsConnectorISpec.scala
Create the API connecting income-tax-benefits backend microservice through to the DES API #1653 - DELETE state benefits API (1653) (in year)
[SASS-1791](https://jira.tools.tax.service.gov.uk/browse/SASS-1791)
=> SASS-1791 add DELETE State Benefit override API

app/connectors/StateBenefitsConnector.scala, app/connectors/httpParsers/GetStateBenefitsHttpParser.scala, app/controllers/StateBenefitsController.scala, app/models/CreateOrUpdatePensionReliefsModel.scala, app/models/GetPensionReliefsModel.scala, app/models/GetStateBenefitsModel.scala, app/services/StateBenefitsService.scala, conf/app.routes, it/api/CreateOrAmendPensionReliefsITest.scala, it/api/GetStateBenefitsITest.scala, it/connectors/PensionReliefsConnectorISpec.scala, it/connectors/StateBenefitsConnectorISpec.scala, test/models/GetPensionReliefsModelSpec.scala, test/models/GetStateBenefitsModelSpec.scala
implemented get state benefits api endpoint
[SASS-1790](https://jira.tools.tax.service.gov.uk/browse/SASS-1790)
- [ x  Have you checked to make sure there are no builds in the pipeline before you merge?
=> implemented get state benefits

app/connectors/StateBenefitsConnector.scala, app/connectors/httpParsers/DeleteStateBenefitsHttpParser.scala, app/controllers/StateBenefitsController.scala, app/models/DesErrorBody.scala, app/services/StateBenefitsService.scala, conf/app.routes, it/api/DeleteOverrideStateBenefitITest.scala, it/api/DeleteStateBenefitITest.scala, it/connectors/StateBenefitsConnectorISpec.scala, project/AppDependencies.scala
Add delete state benefits end of year api endpoint
[SASS-1795](https://jira.tools.tax.service.gov.uk/browse/SASS-1795)
=> SASS-1795 added delete state benefits EOY end point

README.md, app/connectors/PensionIncomeConnector.scala, app/connectors/httpParsers/CreateOrAmendPensionIncomeHttpParser.scala, app/connectors/httpParsers/DeletePensionIncomeHttpParser.scala, app/connectors/httpParsers/GetPensionIncomeHttpParser.scala, app/controllers/GetAllPensionsController.scala, app/controllers/PensionIncomeController.scala, app/models/AllPensionsData.scala, app/models/CreateUpdatePensionIncomeModel.scala, app/models/GetPensionIncomeModel.scala, app/services/PensionIncomeService.scala, app/services/PensionsService.scala, conf/app.routes, it/api/CreateOrAmendPensionIncomeITest.scala, it/api/DeletePensionIncomeITest.scala, it/api/GetPensionIncomeITest.scala, it/connectors/PensionIncomeConnectorISpec.scala, it/helpers/WiremockStubHelpers.scala, test/controllers/GetAllPensionsControllerSpec.scala, test/models/GetPensionIncomeModelSpec.scala, test/services/PensionsServiceSpec.scala, test/utils/TestUtils.scala
Added PUT/DELETE/GET for pension income 
[SASS-3159](https://jira.tools.tax.service.gov.uk/browse/SASS-3159)
=> SASS-3159 Implemented GET/PUT/DELETE for pension Income

README.md, app/config/AppConfig.scala, app/connectors/IFConnector.scala, app/connectors/PensionIncomeConnector.scala, app/connectors/httpParsers/CreateOrAmendPensionIncomeHttpParser.scala, app/connectors/httpParsers/DeletePensionIncomeHttpParser.scala, app/connectors/httpParsers/GetPensionIncomeHttpParser.scala, app/controllers/GetAllPensionsController.scala, app/controllers/PensionIncomeController.scala, app/models/CreateUpdatePensionIncomeModel.scala, app/models/GetPensionIncomeModel.scala, app/services/PensionIncomeService.scala, app/services/PensionsService.scala, conf/app.routes, conf/application.conf, it/api/CreateOrAmendPensionIncomeITest.scala, it/api/DeletePensionIncomeITest.scala, it/api/GetPensionIncomeITest.scala, it/connectors/PensionIncomeConnectorISpec.scala, it/connectors/PensionReliefsConnectorISpec.scala, it/helpers/WiremockSpec.scala, it/helpers/WiremockStubHelpers.scala, test/connectors/IFConnectorSpec.scala, test/controllers/GetAllPensionsControllerSpec.scala, test/models/GetPensionIncomeModelSpec.scala, test/services/PensionsServiceSpec.scala, test/utils/TestUtils.scala
Please include a brief summary of the change you've made and the issue that it fixes.
[SASS-3272](https://jira.tools.tax.service.gov.uk/browse/SASS-3272)
=> Fix pension income tax calls 

.github/PULL_REQUEST_TEMPLATE.md
Please include a brief summary of the change you've made and the issue that it fixes.
[SASS-3339](https://jira.tools.tax.service.gov.uk/browse/SASS-3339)
=> [SASS-3339] Updated based on recent changed to ways of working.

app/controllers/predicates/AuthorisedAction.scala, it/helpers/AuthStub.scala, test/controllers/predicates/AuthorisedActionSpec.scala, test/utils/TestUtils.scala
Jira subtask: SASS-3946
Have you ...
Have you ...
Have you ...
Have you ...
=> SASS-3946 Increase the 'Confidence Level' to 250 from 200

app/connectors/httpParsers/CreateOrAmendPensionIncomeHttpParser.scala, app/connectors/httpParsers/RefreshIncomeSourceHttpParser.scala, app/controllers/PensionIncomeController.scala, app/models/CreateUpdatePensionIncomeModel.scala, app/services/PensionIncomeService.scala, conf/app.routes, it/api/CreateOrAmendPensionIncomeITest.scala, it/connectors/PensionIncomeConnectorISpec.scala, project/AppDependencies.scala, test/services/PensionsIncomeServiceSpec.scala
Jira subtask: SASS-3449
Have you ...
Have you ...
Have you ...
Have you ...
=> SASS-3449 Save Income for overseas pensions CYA to backend

app/models/GetPensionIncomeModel.scala, it/connectors/PensionIncomeConnectorISpec.scala, test/models/GetPensionIncomeModelSpec.scala, test/services/PensionsIncomeServiceSpec.scala, test/utils/TestUtils.scala
Jira subtask: SASS-3449
Have you ...
Have you ...
Have you ...
Have you ...
=> SASS-3449 - Fix income data model issues.

app/services/PensionsService.scala, test/services/PensionsServiceSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
=> SASS-4685 Fixed bug

app/connectors/GetStateBenefitsConnector.scala, app/connectors/httpParsers/GetStateBenefitsHttpParser.scala, it/connectors/GetStateBenefitsConnectorISpec.scala
Jira subtask: SASS-4685
Have you ...
Have you ...
Have you ...
Have you ...
=> SASS-4685 Fix state benefits URL

app/connectors/GetStateBenefitsConnector.scala, app/connectors/httpParsers/GetStateBenefitsHttpParser.scala, it/connectors/GetStateBenefitsConnectorISpec.scala
Reverts hmrc/income-tax-pensions#36
=> Revert "SASS-4685 Fix state benefits URL"

app/connectors/GetStateBenefitsConnector.scala, app/connectors/httpParsers/GetStateBenefitsHttpParser.scala, it/connectors/GetStateBenefitsConnectorISpec.scala
Reverts hmrc/income-tax-pensions#37
=> Revert "Revert "SASS-4685 Fix state benefits URL""

app/connectors/httpParsers/GetStateBenefitsHttpParser.scala, app/models/GetPensionChargesRequestModel.scala, it/api/package.scala, test/models/GetPensionChargesRequestModelSpec.scala, test/services/PensionChargesServiceSpec.scala, test/utils/TestUtils.scala
Jira subtask: SASS-4685 - Updated Pension Models to be the same as API
Have you ...
Have you ...
Have you ...
Have you ...
=> SASS 4685 - Updated Pension Models to be the same as API

app/models/GetPensionChargesRequestModel.scala, it/api/package.scala, project/AppDependencies.scala, test/models/GetPensionChargesRequestModelSpec.scala, test/services/PensionIncomeServiceSpec.scala, test/utils/TestUtils.scala
Updated PensionSavingsTaxCharges model
Have you ...
Have you ...
Have you ...
Have you ...
=> SASS-3445: Implement Saving For 'Check Annual Allowances' CYA Page

project/plugins.sbt
Update autobuild plugin to stop retroactive header updates
=> Update autobuild plugin 

app/config/Module.scala, app/controllers/JourneyStatusController.scala, app/models/common/JourneyNameAndStatus.scala, app/repositories/MongoJourneyAnswersRepository.scala, app/services/JourneyStatusService.scala, conf/app.routes, it/repositories/MongoJourneyAnswersRepositoryISpec.scala, test/controllers/JourneyStatusControllerSpec.scala, test/services/JourneyStatusServiceImplSpec.scala, test/stubs/repositories/StubJourneyAnswersRepository.scala, test/utils/TestUtils.scala
Have you ...
Have you ...
Have you ...
Have you ...
=> [SASS-8074] Add route to get the completion statuses of all journeys from mongo

app/connectors/PensionChargesConnector.scala, app/controllers/JourneyAnswersController.scala, app/controllers/PensionChargesController.scala, app/controllers/PensionReliefsController.scala, app/models/CreateUpdatePensionChargesRequestModel.scala, app/models/GetPensionChargesRequestModel.scala, app/models/database/AnnualAllowancesStorageAnswers.scala, app/models/frontend/AnnualAllowancesAnswers.scala, app/services/PensionsService.scala, conf/app.routes, test/controllers/JourneyAnswersControllerSpec.scala, test/mocks/MockPensionChargesConnector.scala, test/models/database/AnnualAllowancesStorageAnswersSpec.scala, test/models/frontend/AnnualAllowancesAnswersSpec.scala, test/models/frontend/PensionContributionsSpec.scala, test/services/PensionsServiceSpec.scala, test/testdata/annualAllowances.scala, test/testdata/frontend.scala, test/utils/TestUtils.scala
Have you ...
Have you ...
Have you ...
Have you ...
=> [SASS-8098] AnnualAllowances - store database answers

app/connectors/httpParsers/ApiParser.scala, app/connectors/httpParsers/RefreshIncomeSourceHttpParser.scala, app/models/GetPensionChargesRequestModel.scala, app/services/PensionsService.scala, test/connectors/ContentHttpReadsSpec.scala, test/connectors/httpParsers/APIParserSpec.scala, test/models/database/PaymentsIntoPensionsStorageAnswersSpec.scala, test/testdata/transfersIntoOverseasPensions.scala
Have you ...
Have you ...
Have you ...
Have you ...
=> [SASS-8280] Improve TIOP scheme consistency

app/controllers/JourneyAnswersController.scala, app/models/frontend/OverseasPensionScheme.scala, app/models/frontend/PaymentsIntoOverseasPensionsAnswers.scala, app/models/frontend/Relief.scala, app/services/PensionsService.scala, conf/app.routes, test/services/PensionsServiceSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
=> SASS-8221 Get empty journey data from the backend

app/models/charges/PensionSchemeOverseasTransfers.scala, app/models/database/TransfersIntoOverseasPensionsStorageAnswers.scala, app/models/models.scala, app/services/PensionsService.scala, test/models/PensionSchemeOverseasTransfersSpec.scala, test/models/database/TransfersIntoOverseasPensionsStorageAnswersSpec.scala, test/services/PensionsServiceIpmlSpec.scala, test/testdata/connector/getPensionChargesRequestModel.scala
Have you ...
Have you ...
Have you ...
Have you ...
=> [SASS-8374] TIOP - Load prior data from BE DB for 'No' journey

app/controllers/JourneyAnswersController.scala, app/models/charges/OverseasPensionContributions.scala, app/models/database/ShortServiceRefundsStorageAnswers.scala, app/models/frontend/ShortServiceRefundsAnswers.scala, app/services/PensionsService.scala, conf/app.routes, test/models/database/ShortServiceRefundsStorageAnswersSpec.scala, test/models/frontend/ShortServiceRefundsAnswersSpec.scala, test/services/PensionsServiceIpmlSpec.scala, test/stubs/services/PensionsServiceStub.scala, test/testdata/shortServiceRefunds.scala, test/testdata/transfersIntoOverseasPensions.scala
Have you ...
Have you ...
Have you ...
Have you ...
=> [SASS-7919] Get and Save answers for Short Service Refunds

app/controllers/JourneyAnswersController.scala, app/models/charges/OverseasPensionContributions.scala, app/models/charges/OverseasRefundPensionScheme.scala, app/models/charges/OverseasSchemeProvider.scala, app/models/database/ShortServiceRefundsStorageAnswers.scala, app/models/frontend/ShortServiceRefundsAnswers.scala, app/services/PensionsService.scala, test/models/OverseasRefundPensionSchemeSpec.scala, test/models/database/ShortServiceRefundsStorageAnswersSpec.scala, test/models/frontend/ShortServiceRefundsAnswersSpec.scala, test/services/PensionsServiceIpmlSpec.scala, test/testdata/shortServiceRefunds.scala
Jira subtask: SASS-8385
Have you ...
Have you ...
Have you ...
Have you ...
=> [SASS-8385] Fix Journey save
